UPDATE "ProductBuffer" AS pb
SET "buffer" = -1
FROM "Vestiging" AS v
JOIN "Product" AS p
  ON p.id = pb."productId"
JOIN "ProductCategorie" AS pc
  ON pc.id = p."categorieId"
WHERE pb."vestigingId" = v.id
  AND LOWER(v.naam) = 'roermond'
  AND LOWER(pc.naam) = 'ijs';